CLASSES = ['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 'Tomato___healthy']

FERTILIZER_SUGGESTIONS = {
    "Apple___Apple_scab": "Apply fungicides containing captan or copper and ensure proper pruning.",
    "Apple___Black_rot": "Use fungicides containing thiophanate-methyl or myclobutanil.",
    "Apple___Cedar_apple_rust": "Spray sulfur-based fungicides and remove infected leaves.",
    "Apple___healthy": "Maintain a balanced fertilization schedule with nitrogen, phosphorus, and potassium.",
    "Blueberry___healthy": "Use ammonium-based fertilizers and maintain acidic soil conditions (pH 4.5-5.5).",
    "Cherry_(including_sour)___Powdery_mildew": "Apply sulfur-based or potassium bicarbonate fungicides.",
    "Cherry_(including_sour)___healthy": "Use compost or balanced fertilizers rich in potassium and nitrogen.",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Apply strobilurin fungicides and ensure crop rotation.",
    "Corn_(maize)___Common_rust_": "Use fungicides with propiconazole or pyraclostrobin.",
    "Corn_(maize)___Northern_Leaf_Blight": "Apply fungicides containing azoxystrobin or mancozeb.",
    "Corn_(maize)___healthy": "Fertilize with nitrogen-rich fertilizers during the growing season.",
    "Grape___Black_rot": "Use fungicides containing myclobutanil or mancozeb and prune infected vines.",
    "Grape___Esca_(Black_Measles)": "Apply fungicides during the early growing season and improve drainage.",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Use copper-based fungicides and avoid overhead irrigation.",
    "Grape___healthy": "Use balanced fertilizers with potassium, phosphorus, and magnesium.",
    "Orange___Haunglongbing_(Citrus_greening)": "Apply micronutrient sprays and systemic insecticides for psyllid control.",
    "Peach___Bacterial_spot": "Use copper-based bactericides and avoid overhead irrigation.",
    "Peach___healthy": "Fertilize with nitrogen during the early growing season.",
    "Pepper,_bell___Bacterial_spot": "Apply copper-based fungicides and avoid waterlogged conditions.",
    "Pepper,_bell___healthy": "Use balanced fertilizers rich in nitrogen and potassium.",
    "Potato___Early_blight": "Apply fungicides containing chlorothalonil or mancozeb.",
    "Potato___Late_blight": "Use fungicides with fluazinam or mancozeb and ensure good airflow.",
    "Potato___healthy": "Fertilize with balanced NPK fertilizers during tuber development.",
    "Raspberry___healthy": "Use compost or potassium-rich fertilizers to encourage healthy growth.",
    "Soybean___healthy": "Inoculate seeds with rhizobia bacteria and apply phosphorus-rich fertilizers.",
    "Squash___Powdery_mildew": "Spray sulfur-based fungicides or potassium bicarbonate solutions.",
    "Strawberry___Leaf_scorch": "Apply fungicides containing thiophanate-methyl or mancozeb.",
    "Strawberry___healthy": "Use balanced fertilizers with potassium and magnesium for fruit development.",
    "Tomato___Bacterial_spot": "Spray copper-based bactericides and remove infected plants.",
    "Tomato___Early_blight": "Use fungicides containing chlorothalonil or copper-based sprays.",
    "Tomato___Late_blight": "Apply fungicides with mancozeb or chlorothalonil.",
    "Tomato___Leaf_Mold": "Use sulfur-based fungicides and improve ventilation.",
    "Tomato___Septoria_leaf_spot": "Spray fungicides containing mancozeb or copper oxychloride.",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Use miticides or neem oil for control.",
    "Tomato___Target_Spot": "Apply fungicides with azoxystrobin or mancozeb.",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Control whiteflies with systemic insecticides.",
    "Tomato___Tomato_mosaic_virus": "Remove infected plants and disinfect tools.",
    "Tomato___healthy": "Use a balanced fertilizer with calcium and potassium to support growth."
}

ORGANIC_SUGGESTIONS = {
    "Apple___Apple_scab": "Apply **Wettable Sulfur** (2-4 tablespoons per gallon of water) or a **Potassium Bicarbonate spray** (1 tablespoon per gallon of water) weekly, and ensure proper pruning.",
    "Apple___Black_rot": "Apply **Neem Oil** (1-2 oz per gallon of water) every 7-14 days. Focus on meticulous removal of mummified fruit and infected wood.",
    "Apple___Cedar_apple_rust": "Spray with **Sulfur Dust** or **Neem Oil** solution (1-2 oz per gallon). Focus on removing the host juniper species (cedar trees) nearby.",
    "Apple___healthy": "Maintain a balanced fertilization schedule using aged **compost (1-2 inches around the drip line)**, **worm castings**, and **organic fruit tree fertilizer spikes**.",
    "Blueberry___healthy": "Use **Cottonseed Meal or Blood Meal** (1 cup per 10 sq ft) for nitrogen and maintain acidic soil conditions using **Peat Moss or Elemental Sulfur** (follow package instructions for pH adjustment).",
    "Cherry_(including_sour)___Powdery_mildew": "Apply a **Potassium Bicarbonate spray** (1 tablespoon per gallon of water) or use **Neem Oil** (1-2 oz per gallon) weekly.",
    "Cherry_(including_sour)___healthy": "Use **Aged Compost (1-2 inches)**, **Seaweed Extract** (follow label for foliar spray), or **balanced organic fruit fertilizer** rich in potassium and nitrogen.",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Apply **Neem Oil** (1-2 oz per gallon) or a **Copper-based organic fungicide** (follow label). Ensure strict **crop rotation**.",
    "Corn_(maize)___Common_rust_": "Use **Sulfur Dust** (light coating) or **Neem Oil spray** (1-2 oz per gallon) weekly. Plant disease-resistant varieties when possible.",
    "Corn_(maize)___Northern_Leaf_Blight": "Apply a **Neem Oil** solution (1-2 oz per gallon) or **Potassium Bicarbonate spray**. Prioritize using resistant corn varieties.",
    "Corn_(maize)___healthy": "Fertilize with **Composted Chicken Manure** (1/2 cup per plant) or **Fish Emulsion** (follow label for foliar/drench) during the growing season.",
    "Grape___Black_rot": "Use **Sulfur Dust** or **Copper Soap** (follow label for dilution) and ensure rigorous pruning and sanitation of infected vines.",
    "Grape___Esca_(Black_Measles)": "Apply **Copper-based organic fungicides** (follow label) during the dormant and early growing season. Critically **improve drainage** with **aged compost**.",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Use **Copper-based organic fungicides** (follow label) and switch to **drip irrigation** instead of overhead watering.",
    "Grape___healthy": "Use **Aged Compost (1-2 inches)**, **Kelp Meal** (1 cup per vine), or **Wood Ash** (light dust) for balanced organic fertilization.",
    "Orange___Haunglongbing_(Citrus_greening)": "Apply **Foliar Seaweed Extract** or **Compost Tea** (dilute to a light brown color) for micronutrients and use **Pyrethrin or Horticultural Oil** for psyllid control.",
    "Peach___Bacterial_spot": "Use **Copper-based organic bactericides** (follow label, typically multiple dormant applications) and switch to **drip irrigation**.",
    "Peach___healthy": "Fertilize with **Compost, Alfalfa Meal, or Blood Meal** (1 cup per plant) during the early growing season.",
    "Pepper,_bell___Bacterial_spot": "Apply **Copper-based organic fungicides** (follow label) and mix **Compost** into the soil to improve drainage.",
    "Pepper,_bell___healthy": "Use **balanced organic vegetable fertilizers** rich in **Fish Emulsion (follow label)** and **Kelp Meal (1/2 cup per plant)**.",
    "Potato___Early_blight": "Apply **Copper-based organic fungicides or Neem Oil** (1-2 oz per gallon). Practice **hilling** to cover exposed tubers.",
    "Potato___Late_blight": "Use **Copper-based organic sprays** (follow label). Ensure wide plant spacing and **hilling** for good airflow.",
    "Potato___healthy": "Fertilize with **balanced NPK organic fertilizers** during tuber development. Add **Bone Meal or Rock Phosphate** (1/4 cup per plant) for phosphorus.",
    "Raspberry___healthy": "Use **Aged Compost (1-2 inches)** or **Potassium-rich organic sources like Kelp Meal and Wood Ash** (light dressing) to encourage healthy growth.",
    "Soybean___healthy": "**Inoculate seeds with beneficial bacteria** (Rhizobia) and apply **Rock Phosphate or Bone Meal** (follow package instructions) for phosphorus.",
    "Squash___Powdery_mildew": "Spray with a **dilute Milk Solution** (1 part milk to 9 parts water) or **Potassium Bicarbonate** (1 tablespoon per gallon) mixture.",
    "Strawberry___Leaf_scorch": "Apply **Copper-based organic sprays or Neem Oil** (1-2 oz per gallon).",
    "Strawberry___healthy": "Use **balanced organic fertilizers** with **Kelp Meal (potassium)** and **Epsom Salts (magnesium, 1 tablespoon per gallon drench)** for fruit development.",
    "Tomato___Bacterial_spot": "Spray **Copper-based organic bactericides** (follow label) and meticulously remove infected leaves/plants.",
    "Tomato___Early_blight": "Use **Copper-based organic sprays or Neem Oil** (1-2 oz per gallon). **Mulch heavily** (4-6 inches) to prevent soil splash.",
    "Tomato___Late_blight": "Apply **Copper-based organic fungicides** (follow label) and prune lower leaves to improve airflow.",
    "Tomato___Leaf_Mold": "Use **Sulfur-based organic fungicides** (follow label) and ensure the growing area has maximum ventilation.",
    "Tomato___Septoria_leaf_spot": "Spray **Copper Oxychloride** or **Neem Oil** (1-2 oz per gallon). Remove infected leaves immediately.",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Use **Neem Oil** or **Insecticidal Soap** (follow label). Release **beneficial predatory mites** (follow supplier instructions).",
    "Tomato___Target_Spot": "Apply **Copper-based organic sprays** (follow label).",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Control whiteflies with **Yellow Sticky Traps**, **Neem Oil** (1-2 oz per gallon), or **beneficial insects**.",
    "Tomato___Tomato_mosaic_virus": "Remove infected plants. **Disinfect tools with a 1:4 bleach solution or 70% alcohol** and wash hands after handling plants.",
    "Tomato___healthy": "Use a **balanced organic fertilizer** with **Eggshells/Gypsum (calcium)** and **Kelp Meal (potassium)** to support growth."
}